### PR TITLE
Fix segmentation fault when running XDebug 2.9.2 on an M1 mac

### PR DESCRIPTION
**Pull request by tr33m4n**
### Description
On M1 running PHP 7.4 and Xdebug 2.9.2, when attempting to step into a method, strange behaviour would occur in PHPStorm in that Xdebug seemingly would not step into the method, but either segfault with barely any information or break within the same class if the method was inside an iterator.

~~Updating to the latest 2.x version (2.9.8) resolves this. Unfortunately it wasn't too clear which commit may have fixed this, however there are numerous references to segfault's between v2.9.2 and 2.9.8 https://xdebug.org/updates#x_2_9_8~~

Updating to 3.1.4 (the version that PHP 8.1 is currently using) resolves this.

### CODE REVIEW

**Review by liamjtoohey — APPROVED** [review]
Looks fine. We can probs wait until @convenient is back to merge, don't think anyone else has experienced this yet (or has the new M1 chips)

**Comment by tr33m4n** [comment]
@convenient @liamjtoohey Hmm, still seeing issues with this version as well, although not as severe. When attempting to debug recursion, things would die with errors similar to:
```
Return value of Ampersand\D365BusinessCentralOData\Schema\ElementIterator::resolveElementIteration() must be of the type array, unknown returned
```
However, with XDebug disabled, the functionality executes successfully 🤷🏻

**Comment by tr33m4n** [comment]
@liamjtoohey @convenient Right, updated PHP7.4 to use v3.1.4 of XDebug, the same version PHP 8.1 is currently using... Things are looking better!

**Comment by convenient** [comment]
So strange that I never encountered this. must have been whatever specific thing you were debugging triggered it but not for me.

**Comment by convenient** [comment]
https://xdebug.org/docs/compat

Compat says its fine.

**Pull request merged**
